Repository JCSDA-internal/ioda-converters, pull requests merged in 2020-09, with the labels that each got.

#312 CPack support for jedi-build
  CMakeLists.txt
Labels: JEDI1, JEDI5, needs review

#311 Feature/ncep bufr
  CMakeLists.txt
  src/gnssro/CMakeLists.txt
Labels: JEDI1, enhancement, ready for merge

#322 Feature giirs ssec performance
  src/ssec/giirs_ssec2ioda.py
  test/CMakeLists.txt
  test/testoutput/giirs_ssec_ioda.nc4
Labels: JEDI1, JEDI2, enhancement
