Repository JCSDA-internal/ioda-converters, pull requests merged in 2020-11, with the labels that each got.

#357 Move logic enabling the GNSSRO tests back to the root CMakeLists
  CMakeLists.txt
  src/CMakeLists.txt
Labels: JEDI1, bug

#359 Add simple single observation generation script
  src/CMakeLists.txt
  src/single_observation/CMakeLists.txt
  src/single_observation/README.md
  src/single_observation/gen_single_ob.py
  test/CMakeLists.txt
  test/testinput/singleob.yaml
  test/testoutput/singleob.nc
Labels: enhancement, needs review

#364 Remove obsolete odb test files
  test/testinput/aod_viirs_obs_2018041500_s.odb
  test/testinput/odb_sonde_16019.odb
Labels: bug
