Repository JCSDA-internal/ioda-converters, pull requests merged in 2020-08, with the labels that each got.

#300 Add Python IODA-converter for TROPOMI NO2 retrievals
  README.md
  src/chem/CMakeLists.txt
  src/chem/tropomi_no2_nc2ioda.py.in
  test/CMakeLists.txt
  test/testinput/tropomi_no2.nc
  test/testoutput/tropomi_no2.nc
Labels: enhancement, needs review

#304 Performance improvement for NcWriter DateTime conversions
  src/lib-python/ioda_conv_ncio.py
Labels: JEDI1, restructure

#308 Bugfix/pyiodaconv installdir
  CMakeLists.txt
  src/lib-python/CMakeLists.txt
Labels: JEDI1, bug
