Repository JCSDA-internal/ioda-converters, pull requests merged in 2020-04, with the labels that each got.

#266 Improve speed of gsi NCDIAGS IODA obs combining by 10x-30x
  src/gsi-ncdiag/combine_conv.py
  src/gsi-ncdiag/test_gsidiag.py
Labels: enhancement

#269 Feature/l2 oceancolor
  README.md
  src/marine/CMakeLists.txt
  src/marine/viirs_modis_oc2ioda.py.in
  test/CMakeLists.txt
  test/testinput/modis_aqua_oc_l2.nc
  test/testinput/viirs_jpss1_oc_l2.nc
  test/testoutput/modis_aqua_oc_l2.nc
  test/testoutput/viirs_jpss1_oc_l2.nc
Labels: enhancement

#268 Fix unicode encoding errors for station id
  src/lib-python/ioda_conv_ncio.py
Labels: bug, needs review

#272 Fix ncdiags converter utf-8 conversion errors??
  .gitignore
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: bug, waiting for another PR
