Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-07, with the labels that each got.

#591 use python3 explicitly
  src/chem/airnow2ioda-nc.py
  src/chem/tropomi_no2_nc2ioda.py
  src/chem/viirs_aod2ioda.py
  src/gsi-ncdiag/combine_files.py
  src/gsi-ncdiag/proc_gsi_ncdiag.py
  src/gsi-ncdiag/subset_files.py
  src/gsi-ncdiag/test_gsidiag.py
  src/land/smos_ssm2ioda.py
  src/lib-python/collect_sources.py
  src/lib-python/ioda_conv_ncio.py
  src/lib-python/meteo_utils.py
  src/lib-python/run-mccabe.py
  src/lib-python/run-pyflakes.py
  src/marine/argoClim2ioda.py
  src/marine/cryosat_ice2ioda.py
  src/marine/emc_ice2ioda.py
  src/marine/gds2_sst2ioda.py
  src/marine/glider2ioda.py
  src/marine/gmao_obs2ioda.py
  src/marine/godae_profile2ioda.py
  src/marine/godae_ship2ioda.py
  src/marine/godae_trak2ioda.py
  src/marine/hgodas_adt2ioda.py
  src/marine/hgodas_insitu2ioda.py
  src/marine/hgodas_sst2ioda.py
  src/marine/ndbc_hfradar2ioda.py
  src/marine/rads_adt2ioda.py
  src/marine/smap_sss2ioda.py
  src/marine/smos_sss2ioda.py
  src/marine/viirs_modis_l2_oc2ioda.py
  src/marine/viirs_modis_l3_oc2ioda.py
  src/ncep/bufr2nc.py
  src/ncep/bufr2ncCommon.py
  src/ncep/bufr2ncObsTypes.py
  src/ncep/ncep_classes.py
  src/orig/JEDI_amsu_bufr2nc.v8.py
  src/orig/JEDI_conv_bufr2nc_2D.py
  src/orig/prepbufr2ncSG.py
  src/ssec/Experimental/giirs_lw2ioda_bt_v1.py
  src/ssec/Experimental/giirs_lw2ioda_bt_v2.py
  src/ssec/giirs_lw2ioda.py
  src/ssec/giirs_ssec2ioda.py
  src/wrfda-ncdiag/proc_wrfda_ncdiag.py
  src/wrfda-ncdiag/test_wrfdadiag.py
  tools/bufrtest.py
  tools/iodaconv_cpplint.py
Labels: JEDI1

#585 Added ioda converter for MODIS collection 6.1 AOD retrievals, with ne…
  src/chem/CMakeLists.txt
  src/chem/modis_aod2ioda.py
  src/chem/tropomi_no2_nc2ioda.py
  test/CMakeLists.txt
  test/testinput/modis_aod.nc
  test/testoutput/modis_aod.nc
Labels: OBS1, enhancement

#596 Add bufr_version as global attribute to bufr2ioda output (for AMVs only)
  tools/run_satwnds/satwnds_new_subset_template.yaml
  tools/run_satwnds/satwnds_old_subset_template.yaml
Labels: OBS1, OBS3
