Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-03, with the labels that each got.

#448 Addition of LaunchTime (float, unit: hours) to the dictionary of gsi_ncdiag.py.
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: OBS1

#456 Assign dimensions to all variables in satbias files
  src/satbias/SatBiasConverter.cpp
Labels: bug

#460 Add channel dependent metadata for GMI
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: OBS1

#438 Fix to read afwa snow depth lat/lon using pygrib when southern/northern hemisphere grib1 file is read
  src/land/afwa_snod2ioda.py
  src/land/ims_scf2ioda.py
  test/testoutput/afwa_snod.nc
  test/testoutput/imssnow_scf.nc
Labels: Epic, bug, needs review

#436 Initial implementation for ASCAT L2 NRT soil moisture normalized converter
  README.md
  src/land/CMakeLists.txt
  src/land/ascat_ssm2ioda.py
  test/CMakeLists.txt
  test/testinput/ascat_ssm.nc
  test/testoutput/ascat_ssm.nc
Labels: enhancement, needs review

#439 Add support of global attributes
  src/bufr/IodaEncoder/IodaDescription.cpp
  src/bufr/IodaEncoder/IodaDescription.h
  src/bufr/IodaEncoder/IodaEncoder.cpp
  test/testinput/bufr_mhs.yaml
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
Labels: enhancement

#481 Update README.md with instructions on how to build ioda-converters
  README.md
Labels: JEDI2

#465 Feature/adpsfc_snow_example
  test/CMakeLists.txt
  test/testinput/bufr_snow_adpsfc.yaml
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
Labels: update test data

#482 Add AMSR2 to list of radiances in GSI diag converter
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: adaptation complete

#485 Added code to handle the two namings of the bufr interface include file.
  CI/buildspec_clang.yml
  CI/buildspec_gnu.yml
  src/bufr/BufrParser/BufrCollectors/BufrIntCollector.cpp
  src/bufr/BufrParser/BufrCollectors/BufrRepCollector.cpp
  src/bufr/BufrParser/BufrParser.cpp
Labels: bug

#458 Fix to convert multiple CryoSat2 sea-ice freeboard data files into one concatenated daily file
  src/marine/cryosat_ice2ioda.py
Labels: bug, needs review
