Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-10, with the labels that each got.

#617 GOES-16/17 Converter - Enhanced MetaData
  README.md
  src/goes/goes.py
  src/goes/goes_converter.py
  src/goes/goes_latlon.py
  src/goes/goes_util.py
  src/goes/test_goes_converter.py
Labels: JEDI4, JEDI-GDAS

#639 Link to python libraries in "module" mode instead of "embed" mode
  src/lib-python/ioda_conv_engines.py
Labels: JEDI1

#667 Update python converter for METARs to version2
  src/conventional/metar_csv2ioda.py
  test/CMakeLists.txt
  test/testoutput/2020100106_metars_small.nc
Labels: needs review, OBS3, Sprint
