Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-08, with the labels that each got.

#602 Feature/aeronet2ioda aod
  src/chem/CMakeLists.txt
  src/chem/aeronet_aod2ioda.py
  test/CMakeLists.txt
  test/testinput/aeronet_aod.dat
  test/testoutput/aeronet_aod.nc
Labels: OBS1

#605 Feature/gnssro netcdf4 fix
  src/gnssro/README
  src/gnssro/gnssro_gsidiag2ioda.f90
Labels: needs review, ready for merge

#604 Initial Implementation of IODAv2 Python Converter
  CMakeLists.txt
  src/chem/tropomi_no2_nc2ioda.py
  src/lib-python/CMakeLists.txt
  src/lib-python/ioda_conv_engines.py
  test/CMakeLists.txt
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/satbias_amsua_n18.nc4
  test/testoutput/satbias_cris_npp.nc4
  test/testoutput/satbias_ssmis_f16.nc4
  test/testoutput/tropomi_no2.nc
Labels: needs review
