Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-11, with the labels that each got.

#678 Test reference file updates according to new default initialization for dimension scale variables
  test/testoutput/2020100106_metars_small.nc
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/airep_multi.nc
  test/testoutput/amdar_single.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc
  test/testoutput/ioda_global_vavh_l3_rt_s3a_20210930T18.nc
  test/testoutput/satbias_amsua_n18.nc4
  test/testoutput/satbias_cris_npp.nc4
  test/testoutput/satbias_ssmis_f16.nc4
  test/testoutput/tropomi_no2.nc
Labels: needs review

#687 CMake Update for GOES-16/17 Converter
  src/goes/CMakeLists.txt
Labels: JEDI4

#673 Feature/v2 godae ship
  src/marine/godae_ship2ioda.py
  test/CMakeLists.txt
  test/testoutput/godae_ship.nc
Labels: OBS3

#676 Update godae_trak converter to iodav2
  src/marine/godae_trak2ioda.py
  test/CMakeLists.txt
  test/testoutput/godae_trak.nc
Labels: OBS3, Sprint

#661 Feature/v2 smap sss2iod
  src/marine/smap_sss2ioda.py
  test/CMakeLists.txt
  test/testoutput/smap_sss_rss.nc
Labels: SOCA2

#662 Feature/v2 smos sss2ioda
  src/marine/smos_sss2ioda.py
  test/CMakeLists.txt
  test/testoutput/smos_sss_l2.nc
Labels: SOCA2

#663 Feature/v2 rads adt
  src/marine/rads_adt2ioda.py
  test/CMakeLists.txt
  test/testoutput/rads_adt.nc
Labels: ready for merge

#672 Feature/v2land
  src/land/afwa_snod2ioda.py
  src/land/ascat_ssm2ioda.py
  src/land/ghcn_snod2ioda.py
  src/land/ims_scf2ioda.py
  src/land/smap_ssm2ioda.py
  src/land/smos_ssm2ioda.py
  test/CMakeLists.txt
  test/testoutput/afwa_snod.nc
  test/testoutput/ascat_ssm.nc
  test/testoutput/ghcn_snod_20200228.nc
  test/testoutput/imssnow_scf.nc
  test/testoutput/smap_ssm.nc
  test/testoutput/smos_ssm.nc
Labels: enhancement, ready for merge, OBS3, LAND, Sprint

#683 Feature/ims fv3 v2
  src/land/CMakeLists.txt
  src/land/imsfv3_scf2ioda.py
  test/CMakeLists.txt
  test/testinput/imsscf_20191215_c48.nc
  test/testoutput/imsfv3_scf.nc
Labels: enhancement, OBS3, LAND, Sprint

#681 modified emc_ice2ioda.py to output ioda_v2 and created test files
  src/marine/emc_ice2ioda.py
  test/CMakeLists.txt
  test/testinput/emc_ice.nc
  test/testoutput/emc_ice_ioda2.nc
Labels: SOCA2, Sprint

#696 Repaired list initialization in GOES-16/17 IODA converter.
  src/goes/goes_converter.py
Labels: JEDI4

#685 Upgrade ghcn snow depth converter
  src/land/ghcn_snod2ioda.py
  test/testoutput/ghcn_snod_20200228.nc
Labels: Epic, OBS3, LAND

#690 Upgrade hgodas_adt2ioda to use ioda-v2 and add tests
  src/marine/hgodas_adt2ioda.py
  test/CMakeLists.txt
  test/testinput/hgodas_adt.nc
  test/testoutput/hgodas_adt.nc
Labels: OBS3

#694 upgrade airnow2ioda converter
  src/chem/airnow2ioda-nc.py
  test/testoutput/airnow_2020081306.nc
Labels: COMPO

#700 Add ability to convert GNSSRO data in WMO-formatted BUFR to IODA (v2) output
  doc/bufr_obs_samples/gnssro_bufr_sample.txt
  doc/bufr_table_samples/gnssro_bufr_mnemonics.txt
  test/CMakeLists.txt
  test/testinput/gnssro_2020-306-2358C2E6.bufr
  test/testinput/gnssro_wmoBUFR2ioda.yaml
  test/testoutput/gnssro_2020-306-2358C2E6.nc
Labels: OBS1
