Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-05, with the labels that each got.

#533 Fix to get working with ecbuild 3.6.1
  src/bufr/CMakeLists.txt
Labels: OBS3

#531 Addition of avhrr3 naming for GSI ncdiag files
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: JEDI-GDAS

#534 IODA Version 2
  CI/CMakeLists.txt
  CI/buildspec_clang.yml
  CI/buildspec_gnu.yml
  CI/buildspec_intel.yml
  src/bufr/IodaEncoder/IodaEncoder.cpp
  src/satbias/SatBiasConverter.cpp
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
Labels: JEDI1, OBS3, coordinate merge

#535 For usage in surface data files in UFO, the height variable (metadata) is needed; so it was added
  src/conventional/metar_csv2ioda.py
  test/testoutput/2020100106_metars_small.nc
Labels: OBS3, update test data

#554 Changes to support prsi in geovals
  src/gsi-ncdiag/combine_files.py
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: JEDI-GDAS, OBS1

#555 Feature/gnssro gsi2ioda
  src/gnssro/CMakeLists.txt
  src/gnssro/README
  src/gnssro/gnssro_gsidiag2ioda.f90
Labels: JEDI-GDAS, OBS1

#473 Added yamls for AIRS, AMSUA, ATMS, MHS, SSMIS sensors following the new IODA naming convention
  doc/bufr_table_samples/satellite_AIRS_mnemonics.txt
  doc/bufr_table_samples/satellite_AMSUA_mnemonics.txt
  doc/bufr_table_samples/satellite_ATMS_mnemonics.txt
  doc/bufr_table_samples/satellite_AVHRR_mnemonics.txt
  doc/bufr_table_samples/satellite_CRIS_mnemonics.txt
  doc/bufr_table_samples/satellite_HIRS_mnemonics.txt
  doc/bufr_table_samples/satellite_MHS_mnemonics.txt
  doc/bufr_table_samples/satellite_SEVCSR_mnemonics.txt
  doc/bufr_table_samples/satellite_SSMIS_mnemonics.txt
  satellite_SEVCSR_mnemonics.txt
  test/testinput/bufr_airs_v2.yaml
  test/testinput/bufr_amsua_v2.yaml
  test/testinput/bufr_atms_v2.yaml
  test/testinput/bufr_avhrr_v2.yaml
  test/testinput/bufr_cris_v2.yaml
  test/testinput/bufr_hirs_v2.yaml
  test/testinput/bufr_mhs_v2.yaml
  test/testinput/bufr_sevcrs_v2.yaml
  test/testinput/bufr_ssmis_v2.yaml
Labels: OBS1, needs review, update test data

#573 add adpsfc and aircft individual bufr tables to ioda-coverters
  doc/bufr_table_samples/adpsfc.nc000000.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000001.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000002.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000007.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000010.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000011.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000100.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000101.bufr.table.txt
  doc/bufr_table_samples/adpsfc.nc000102.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004001.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004002.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004003.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004004.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004006.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004009.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004010.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004011.bufr.table.txt
  doc/bufr_table_samples/aircft.nc004103.bufr.table.txt
Labels: documentation
