Repository JCSDA-internal/ioda-converters, pull requests merged in 2021-12, with the labels that each got.

#692 Feature/hgodas sst2ioda v2
  src/marine/hgodas_sst2ioda.py
  test/CMakeLists.txt
  test/testoutput/hgodas_sst.nc
Labels: SOCA2

#698 Feature/v2 viirs modis l3 oc
  src/marine/viirs_modis_l3_oc2ioda.py
  test/CMakeLists.txt
  test/testoutput/viirs_jpss1_oc_l3.nc
Labels: OBS3

#715 Add support for WMO-formatted BUFR files of 2 satellite wind (AMV) sources: EU_MetSat and Himawari
  doc/bufr_obs_samples/satwind_EUMet_bufr_sample.txt
  doc/bufr_table_samples/satwind_EUMet_mnemonics.txt
  doc/bufr_table_samples/satwind_Himawari_bufr_sample.txt
  doc/bufr_table_samples/satwind_Himawari_mnemonics.txt
  test/CMakeLists.txt
  test/testinput/satwind_EUMet_wmo.bufr
  test/testinput/satwind_EUMet_wmoBUFR2ioda.yaml
  test/testinput/satwind_Himawari_wmo.bufr
  test/testinput/satwind_Himawari_wmoBUFR2ioda.yaml
  test/testoutput/satwind_EUMet.nc
  test/testoutput/satwind_Himawari.nc
Labels: OBS3

#701 upgrade viirs_modis_l2_oc to use iodav2
  src/marine/viirs_modis_l2_oc2ioda.py
  test/CMakeLists.txt
  test/testoutput/modis_aqua_oc_l2.nc
  test/testoutput/viirs_jpss1_oc_l2.nc
Labels: OBS3

#702 Feature/gds2 sst2ioda v2
  src/marine/gds2_sst2ioda.py
  test/CMakeLists.txt
  test/testoutput/gds2_sst_l2p.nc
  test/testoutput/gds2_sst_l3u.nc
Labels: SOCA2

#674 Upgrade chem/aeronet aod and aaod converter to IODA V2 API
  src/chem/aeronet_aaod2ioda.py
  src/chem/aeronet_aod2ioda.py
  test/CMakeLists.txt
  test/testoutput/aeronet_aaod.nc
  test/testoutput/aeronet_aod.nc
Labels: OBS3, COMPO

#680 Upgrade Python converter for (ndbc_hfradar2ioda.py) to IODA-v2 & Add DOPX DOPY pre-processing quality flag: HF radar
  src/marine/ndbc_hfradar2ioda.py
  test/CMakeLists.txt
  test/testoutput/ndbc_hfradar_out.nc
Labels: enhancement, SOCA2, Sprint

#714 Add support for WMO-formatted BUFR files of 3 surface data types: Ship, Buoy, SYNOP
  doc/bufr_obs_samples/buoy_bufr_sample.txt
  doc/bufr_obs_samples/ship_bufr_sample.txt
  doc/bufr_obs_samples/synop_bufr_sample.txt
  doc/bufr_table_samples/buoy_bufr_mnemonics.txt
  doc/bufr_table_samples/ship_bufr_mnemonics.txt
  doc/bufr_table_samples/synop_bufr_mnemonics.txt
  test/CMakeLists.txt
  test/testinput/buoy_wmoBUFR2ioda.yaml
  test/testinput/buoy_wmo_single.bufr
  test/testinput/ship_wmoBUFR2ioda.yaml
  test/testinput/ship_wmo_single.bufr
  test/testinput/synop_wmoBUFR2ioda.yaml
  test/testinput/synop_wmo_single.bufr
  test/testoutput/buoy_single.nc
  test/testoutput/ship_single.nc
  test/testoutput/synop_single.nc
Labels: OBS3

#725 New marine converter: godae BGC-Argo profiles
  src/marine/CMakeLists.txt
  src/marine/godae_bgc_argo2ioda.py
  test/CMakeLists.txt
  test/testinput/godae_bgc_argo.nc
  test/testoutput/godae_bgc_argo.nc
Labels: enhancement

#724 Feature/add noaa nomads ingest script
  tools/ingest/retrieve_data_from_noaa_nomads.sh
Labels: needs review

#718 Feature/add atms ingest scripts
  tools/ingest/retrieve_atms_from_nasa.sh
Labels: needs review, OBS3

#729 Feature/avk vertcoord
  src/chem/tropomi_no2_nc2ioda.py
  test/testoutput/tropomi_no2.nc
Labels: OBS3, COMPO

#668 Change modis_aod2ioda.py to v2
  src/chem/modis_aod2ioda.py
  test/CMakeLists.txt
  test/testoutput/modis_aod.nc
Labels: COMPO

#642 Feature/v2profile
  src/marine/godae_profile2ioda.py
  src/marine/hgodas_insitu2ioda.py
  test/CMakeLists.txt
  test/testoutput/godae_prof.nc
  test/testoutput/hgodas_insitu.nc
Labels: JEDI1, OBS3
