Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-05, with the labels that each got.

#873 Feature/sprint ioda converters ne viirs modis l2 oc2ioda
  src/marine/argoClim2ioda.py
  src/marine/viirs_modis_l2_oc2ioda.py
  test/testoutput/modis_aqua_oc_l2.nc
  test/testoutput/viirs_jpss1_oc_l2.nc
Labels: OBS3

#934 fix for performance bug in sat winds
  src/conventional/amv_ssec_ascii2ioda.py
Labels: optimization

#929 Feature/sprint ioda converters ne viirs modis l3 oc2ioda
  src/marine/viirs_modis_l3_oc2ioda.py
  test/testoutput/viirs_jpss1_oc_l3.nc
Labels: OBS3

#937 Sprint: update src/marine/gds2_sst2ioda.py code for JEDI Data Conventions
  src/marine/gds2_sst2ioda.py
  test/testoutput/gds2_sst_l2p.nc
  test/testoutput/gds2_sst_l3u.nc
Labels: OBS3, Sprint

#930 Feature/pace oc2ioda
  src/marine/CMakeLists.txt
  src/marine/pace_oc2ioda.py
  test/CMakeLists.txt
  test/testinput/pace_oc_l2.nc
  test/testoutput/pace_oc_l2.nc
Labels: SOCA1

#938 Change optional arguments in viirs_aod2ioda.py to be required.
  src/compo/viirs_aod2ioda.py
Labels: COMPO

#906 update two yaml files via query_cxx
  test/CMakeLists.txt
  test/testinput/bufr_ncep_sevcsr.yaml
  test/testinput/bufr_ncep_snow_adpsfc.yaml
  test/testinput/bufr_read_2_dim_blocks.yaml
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/gdas.t00z.sevcsr.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
Labels: Epic, ready for merge, OBS3, LAND
