Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-03, with the labels that each got.

#800 add some additional error handling for BUFR decode or raob
  src/conventional/decode_bufr_LDM_raob.py
Labels: OBS1, OBS3

#802 Feature/atms multi threaded converter
  src/hdf5/atms_netcdf_hdf5_2ioda.py
Labels: OBS1, OBS3

#810 use_eccodes in CI
  CI/buildspec_clang.yml
  CI/buildspec_gnu.yml
  CI/buildspec_intel.yml
Labels: ready for merge

#807 Python script to convert WMO-formatted BUFR messages of AMDARs (aircraft obs) to IODA
  CMakeLists.txt
  src/conventional/CMakeLists.txt
  src/conventional/amdar_bufr2ioda.py
  test/CMakeLists.txt
  test/testoutput/amdar_wmo_multi2.nc
Labels: OBS3

#812 Python script to convert WMO-formatted BUFR messages of SYNOPs (surface obs) to IODA
  src/conventional/CMakeLists.txt
  src/conventional/synop_bufr2ioda.py
  test/CMakeLists.txt
  test/testoutput/synop_wmo_multi2.nc
Labels: OBS3

#816 Python script to convert WMO-formatted BUFR messages of Ship data (surface obs) to IODA
  src/conventional/CMakeLists.txt
  src/conventional/ship_bufr2ioda.py
  test/CMakeLists.txt
  test/testoutput/ship_wmo_multi2.nc
Labels: OBS3

#818 Python script to convert WMO-formatted BUFR messages of Buoy data (surface obs) to IODA
  src/conventional/CMakeLists.txt
  src/conventional/buoy_bufr2ioda.py
  test/CMakeLists.txt
  test/testoutput/buoy_wmo_multi2.nc
Labels: OBS3

#838 SPRINT: Change METAR converter to align variable names with JEDI naming conventions
  src/conventional/metar_csv2ioda.py
  test/testoutput/2020100106_metars_small.nc
Labels: OBS3, Sprint

#835 BUGFIX: Deal with BUFR msg that has more array elements than what was expected (truncate away extras)
  src/conventional/amdar_bufr2ioda.py
Labels: OBS3

#844 Feature/ioda sprint atms hdf5
  src/hdf5/atms_netcdf_hdf5_2ioda.py
  test/testinput/SNDR.SNPP.ATMS.20211206T0100.m06.g011.L1B.std.v03_15.G.211206074531.nc4
  test/testoutput/2021120600_atms_sdr.nc4
Labels: OBS1, OBS3, Sprint

#806 Bugfix/owp snow obs metadatatypes
  src/land/owp_snow_obs.py
  test/testoutput/owp_snow_obs_dup_thin_err_fn.nc
Labels: needs review, LAND

#856 Sprint: Upgrade converters that use bufr2ioda.x to follow the JEDI Data Conventions
  src/bufr/IodaEncoder/IodaEncoder.cpp
  test/testinput/aircar_BUFR2ioda.yaml
  test/testinput/airep_wmoBUFR2ioda.yaml
  test/testinput/amdar_wmoBUFR2ioda.yaml
  test/testinput/buoy_wmoBUFR2ioda.yaml
  test/testinput/gnssro_wmoBUFR2ioda.yaml
  test/testinput/rass_wmoBUFR2ioda.yaml
  test/testinput/satwind_EUMet_wmoBUFR2ioda.yaml
  test/testinput/satwind_Himawari_wmoBUFR2ioda.yaml
  test/testinput/satwind_Insat_wmoBUFR2ioda.yaml
  test/testinput/ship_wmoBUFR2ioda.yaml
  test/testinput/synop_wmoBUFR2ioda.yaml
  test/testinput/vadwinds_wmoBUFR2ioda.yaml
  test/testoutput/airep_multi.nc
  test/testoutput/amdar_wmo_multi.nc
  test/testoutput/buoy_wmo_multi.nc
  test/testoutput/gdas.aircar.t00z.20210801.nc
  test/testoutput/gnssro_2020-306-2358C2E6.nc
  test/testoutput/rass_wmo_multi.nc
  test/testoutput/satwind_EUMet.nc
  test/testoutput/satwind_Himawari.nc
  test/testoutput/satwind_Insat.nc
  test/testoutput/ship_wmo_multi.nc
  test/testoutput/synop_wmo_multi.nc
  test/testoutput/vadwinds_wmo_multi.nc
Labels: OBS3, Sprint

#863 SPRINT: Upgrade conventional data BUFR-to-IODA converters (shown below) to follow the JEDI Data Conventions
  src/conventional/amdar_bufr2ioda.py
  src/conventional/buoy_bufr2ioda.py
  src/conventional/ship_bufr2ioda.py
  src/conventional/synop_bufr2ioda.py
  test/testoutput/amdar_wmo_multi2.nc
  test/testoutput/buoy_wmo_multi2.nc
  test/testoutput/ship_wmo_multi2.nc
  test/testoutput/synop_wmo_multi2.nc
Labels: OBS3, Sprint

#854 Create Feature/sprint ghcn for 6 land converters during the ioda-converter code spring
  src/land/ghcn_snod2ioda.py
  src/land/imsfv3_scf2ioda.py
  src/land/owp_snow_obs.py
  src/land/smap9km_ssm2ioda.py
  src/land/smap_ssm2ioda.py
  src/land/smos_ssm2ioda.py
  test/testoutput/ghcn_snod_20200228.nc
  test/testoutput/imsfv3_scf.nc
  test/testoutput/owp_snow_obs_dup_thin_err_fn.nc
  test/testoutput/smap9km_ssm.nc
  test/testoutput/smap_ssm.nc
  test/testoutput/smos_ssm.nc
Labels: OBS3, LAND, Sprint

#858 Modify marine/smos_sss, marine/smap_sss, and marine/hgodas_sst converters to follow JEDI data convention
  src/marine/hgodas_sst2ioda.py
  src/marine/smap_sss2ioda.py
  src/marine/smos_sss2ioda.py
  test/testoutput/hgodas_adt.nc
  test/testoutput/hgodas_insitu.nc
  test/testoutput/hgodas_sst.nc
  test/testoutput/smap_sss_rss.nc
  test/testoutput/smos_sss_l2.nc
Labels: ready for merge

#851 Feature/sprint modis aod converters hb
  src/compo/modis_aod2ioda.py
  test/testoutput/modis_aod.nc
Labels: OBS3, Sprint

#883 Remove two land converters with grib input
  README.md
  src/land/CMakeLists.txt
  src/land/afwa_snod2ioda.py
  src/land/ims_scf2ioda.py
  test/CMakeLists.txt
  test/testinput/afwa_snod_24km.grib
  test/testinput/imssnow_24km.grib2
  test/testoutput/afwa_snod.nc
  test/testoutput/imssnow_scf.nc
Labels: Epic, OBS3, LAND, Sprint

#891 Feature/sprint ioda greg bufr2ioda3
  test/testinput/gdas.t18z.1bmhs.tm00.bufr_d
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
Labels: needs review, OBS3, Sprint
