Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-09, with the labels that each got.

#1042 Added satbias converter for gmi_gpm.
  test/CMakeLists.txt
  test/testinput/satbias_converter.yaml
  test/testinput/satbias_converter_gmi_gpm.yaml
  test/testoutput/satbias_gmi_gpm.nc4
Labels: enhancement

#1043 add ompslpnc for geos adas along with cleanup.
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: ready for merge

#1038 Add variable for GNSS bending angle data, save orginal GSI QC flags a…
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: enhancement

#1034 Updated adpsfc types
  test/testinput/bufr_ncep_adpsfc.yaml
  test/testinput/bufr_ncep_prepbufr_adpsfc.yaml
  test/testoutput/gdas.t12z.adpsfc.prepbufr.nc
  test/testoutput/gdas.t12z.adpsfc.tm00.nc
Labels: ready for merge

#1040 Feature/query dim naming bug
  src/bufr/IodaEncoder/IodaEncoder.cpp
  test/CMakeLists.txt
  tools/bufr/print_queries.cpp
Labels: ready for merge

#1058 ioda converter for synthetic SWOT observations
  src/marine/CMakeLists.txt
  src/marine/swot_l2adt2ioda.py
  test/CMakeLists.txt
  test/testinput/SWOT_L2_SSHA.nc
  test/testoutput/SWOT_L2_ADT.nc
Labels: ready for merge

#1053 Fix reference to oz_sensors in proc_gsi_ncdiag
  src/gsi-ncdiag/proc_gsi_ncdiag.py
Labels: ready for merge

#1060 Add ability to convert Text radiosonde data (TEMP format) to IODA
  share/raob_stations.json
  share/raob_stations_small.json
  src/conventional/CMakeLists.txt
  src/conventional/sonde_tac2ioda.py
  src/lib-python/CMakeLists.txt
  src/lib-python/meteo_sounding_utils.py
  test/CMakeLists.txt
  test/testinput/2021081612_RAOB_small.txt
  test/testoutput/2021081612_sonde_small.nc
Labels: OBS, AOP22

#1046 Updated viirs_aod2ioda.py to include nchans for channel number
  src/compo/viirs_aod2ioda.py
  test/testoutput/viirs_aod.nc
Labels: ready for merge

#1044 Feature/query cxx types
  src/bufr/BufrParser/BufrParser.cpp
  src/bufr/BufrParser/Exports/Export.cpp
  src/bufr/BufrParser/Exports/Variables/QueryVariable.cpp
  src/bufr/BufrParser/Exports/Variables/QueryVariable.h
  src/bufr/BufrParser/Exports/Variables/Transforms/OffsetTransform.cpp
  src/bufr/BufrParser/Exports/Variables/Transforms/ScalingTransform.cpp
  src/bufr/BufrParser/Exports/Variables/Variable.h
  src/bufr/BufrParser/Query/Constants.h
  src/bufr/BufrParser/Query/DataProvider.cpp
  src/bufr/BufrParser/Query/DataProvider.h
  src/bufr/BufrParser/Query/File.cpp
  src/bufr/BufrParser/Query/Query.cpp
  src/bufr/BufrParser/Query/Query.h
  src/bufr/BufrParser/Query/ResultSet.cpp
  src/bufr/BufrParser/Query/ResultSet.h
  src/bufr/BufrParser/Query/SubsetTable.cpp
  src/bufr/BufrParser/Query/SubsetTable.h
  src/bufr/BufrParser/Query/Target.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.cpp
  src/bufr/DataObject.h
  src/bufr/README.md
  test/testinput/ADPUPA.prepbufr
  test/testinput/adpupa_prepbufr.yaml
  test/testinput/bufr_ncep_adpsfc.yaml
  test/testinput/bufr_ncep_mtiasi.yaml
  test/testinput/bufr_ncep_prepbufr_adpsfc.yaml
  test/testinput/bufr_ncep_sevcsr.yaml
  test/testinput/gdas.t12z.adpsfc.prepbufr
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/adpupa_prepbufr.nc
  test/testoutput/bufr_empty_fields.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/bufr_sfcshp.nc
  test/testoutput/bufr_simple_groupby.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t00z.sevcsr.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t12z.1bamua.metop-c.tm00.nc
  test/testoutput/gdas.t12z.1bamua.noaa-15.tm00.nc
  test/testoutput/gdas.t12z.1bmhs.metop-b.tm00.nc
  test/testoutput/gdas.t12z.adpsfc.prepbufr.nc
  test/testoutput/gdas.t12z.adpsfc.tm00.nc
  test/testoutput/gdas.t12z.esamua.noaa-18.tm00.nc
  test/testoutput/gdas.t12z.esmhs.noaa-19.tm00.nc
  test/testoutput/gdas.t12z.mtiasi.metop-c.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/gdas.t18z.satwnd_avhrr.tm00.nc
  tools/bufr/print_queries.cpp
Labels: ready for merge

#1059 Feature/query datetime subset fix
  src/bufr/BufrParser/BufrParser.cpp
  src/bufr/BufrParser/Exports/Export.cpp
  src/bufr/BufrParser/Exports/Export.h
  src/bufr/BufrParser/Exports/Splits/CategorySplit.cpp
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp
  src/bufr/BufrParser/Query/File.cpp
  src/bufr/BufrParser/Query/QueryParser.cpp
  src/bufr/BufrParser/Query/QueryParser.h
  src/bufr/BufrParser/Query/QueryRunner.cpp
  src/bufr/BufrParser/Query/QueryRunner.h
  src/bufr/BufrParser/Query/QuerySet.cpp
  src/bufr/BufrParser/Query/QuerySet.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.h
  src/bufr/README.md
  test/CMakeLists.txt
  test/testinput/bufr_specific_subsets_by_query.yaml
  test/testinput/bufr_specifying_subsets.yaml
  test/testinput/gdas.t12z.aircft.tm00.bufr_d
  test/testoutput/bufr_specifying_subsets.nc
Labels: waiting for another PR

#1062 Feature/pace l1b converter
  src/marine/CMakeLists.txt
  src/marine/pace_radiance2ioda.py
  test/CMakeLists.txt
  test/testinput/pace_radiance_L1B.nc
  test/testoutput/pace_radiance_L1B.nc
Labels: ready for merge

#1055 Feature/query labeled dims
  src/bufr/BufrParser/BufrParser.cpp
  src/bufr/BufrParser/Exports/Export.cpp
  src/bufr/BufrParser/Exports/Export.h
  src/bufr/BufrParser/Exports/Splits/CategorySplit.cpp
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp
  src/bufr/BufrParser/Query/File.cpp
  src/bufr/BufrParser/Query/QueryParser.cpp
  src/bufr/BufrParser/Query/QueryParser.h
  src/bufr/BufrParser/Query/QueryRunner.cpp
  src/bufr/BufrParser/Query/QueryRunner.h
  src/bufr/BufrParser/Query/QuerySet.cpp
  src/bufr/BufrParser/Query/QuerySet.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.h
  src/bufr/IodaEncoder/IodaDescription.cpp
  src/bufr/IodaEncoder/IodaDescription.h
  src/bufr/IodaEncoder/IodaEncoder.cpp
  src/bufr/IodaEncoder/IodaEncoder.h
  src/bufr/README.md
  test/CMakeLists.txt
  test/testinput/bufr_hrs.yaml
  test/testinput/bufr_mhs.yaml
  test/testinput/bufr_specific_subsets_by_query.yaml
  test/testinput/bufr_specifying_subsets.yaml
  test/testinput/gdas.t12z.aircft.tm00.bufr_d
  test/testoutput/bufr_specifying_subsets.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
Labels: needs review, ready for merge
