Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-07, with the labels that each got.

#1005 Handle other types of Exceptions, some BUFR messages for SYNOP data has badly formed strings
  src/conventional/synop_bufr2ioda.py
Labels: OBS

#949 Updated DatetimeVariable.cpp code for optional value of Minute
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp
  test/testinput/bufr_ncep_adpupa_minu.yaml
  test/testinput/gdas.t12z.adpupa.tm00.bufr_d
  test/testoutput/bufr_ncep_adpupa_minu.nc
Labels: enhancement

#995 Handling BUFR subsets properly
  src/conventional/decode_bufr_LDM_raob.py
  test/CMakeLists.txt
  test/testoutput/wmo_raob_double.nc4
  test/testoutput/wmo_raob_quadruple.nc4
Labels: needs review, waiting for another PR, OBS

#1012 Update test reference files for the new default fill value for the dateTime variable.
  src/compo/mls_o3_nc2ioda.py
  src/compo/omi_o3_nc2ioda.py
  src/compo/ompsnm_o3_nc2ioda.py
  src/lib-python/ioda_conv_engines.py
  test/testoutput/mls_o3_l2.nc
  test/testoutput/omi_o3_l2.nc
  test/testoutput/ompsnm_o3_l2.nc
Labels: bug
