Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-04, with the labels that each got.

#887 SPRINT: upgrade radiosonde python-eccodes bufr (WMO) converter to JEDI Data Conventions
  doc/bufr_obs_samples/sonde_bufr_sample.txt
  doc/bufr_table_samples/sonde_bufr_mnemonics.txt
  src/conventional/CMakeLists.txt
  src/conventional/decode_bufr_LDM_raob.py
  src/conventional/ship_bufr2ioda.py
  src/conventional/sonde_bufr2ioda.py
  test/CMakeLists.txt
  test/testinput/sonde_wmo_double.bufr
  test/testinput/sonde_wmo_multi.bufr
  test/testoutput/sonde_wmo_multi.nc
  test/testoutput/wmo_raob_double.nc4
  test/testoutput/wmo_raob_quadruple.nc4
Labels: OBS3, Sprint

#884 Replace nlocs with Location, reduce the size of ADPUPA.prepbufr and …
  src/bufr/IodaEncoder/IodaEncoder.cpp
  src/gnssro/gnssro_bufr2ioda.f90
  src/gnssro/gnssro_bufr2ioda.py
  test/testinput/ADPUPA.prepbufr
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/adpupa_prepbufr.nc
  test/testoutput/adpupa_prepbufr_group_by.nc
  test/testoutput/bufr_empty_fields.nc
  test/testoutput/bufr_mtiasi.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/bufr_sfcshp.nc
  test/testoutput/bufr_simple_groupby.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t12z.1bamua.tm00.metop-b.nc
  test/testoutput/gdas.t12z.1bmhs.tm00.metop-b.nc
  test/testoutput/gdas.t12z.esamua.tm00.noaa-18.nc
  test/testoutput/gdas.t12z.esamua.tm00.noaa-19.nc
  test/testoutput/gdas.t12z.esmhs.tm00.noaa-19.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
Labels: enhancement

#849 Feature/sprint aeronet converters hb
  src/compo/aeronet_aaod2ioda.py
  src/compo/aeronet_aod2ioda.py
  test/testoutput/aeronet_aaod.nc
  test/testoutput/aeronet_aod.nc
Labels: OBS3

#889 Feature/tropics satellite ioda converter
  src/hdf5/tropics_2ioda.py
Labels: ready for merge

#895 Sprint: Update the GODAE (marine) converters listed below to adopt the JEDI Data Conventions
  src/marine/argoClim2ioda.py
  src/marine/godae_bgc_argo2ioda.py
  src/marine/godae_profile2ioda.py
  src/marine/godae_ship2ioda.py
  src/marine/godae_trak2ioda.py
  src/marine/smap_sss2ioda.py
  src/marine/smos_sss2ioda.py
  test/testoutput/godae_bgc_argo.nc
  test/testoutput/godae_prof.nc
  test/testoutput/godae_ship.nc
  test/testoutput/godae_trak.nc
Labels: needs review, OBS3, Sprint

#848 Feature/sprint ioda converters fcvdb
  src/land/ascat_ssm2ioda.py
  src/land/owp_snow_obs.py
  test/testoutput/ascat_ssm.nc
Labels: needs review, OBS3, Sprint

#896 Update three marine converters for ioda-converters code sprint
  src/land/smap9km_ssm2ioda.py
  src/marine/glider2ioda.py
  src/marine/hgodas_insitu2ioda.py
  src/marine/ndbc_hfradar2ioda.py
  test/testoutput/hgodas_insitu.nc
  test/testoutput/ndbc_hfradar_out.nc
  test/testoutput/smap9km_ssm.nc
  test/testoutput/test_glider.nc
Labels: OBS3, SOCA2, Sprint

#899 SPRINT: update 3 marine converters to follow JEDI Data Conventions
  src/marine/gmao_obs2ioda.py
  src/marine/hgodas_adt2ioda.py
  src/marine/rads_adt2ioda.py
  test/CMakeLists.txt
  test/testinput/gmao-obs-20180415.nc
  test/testoutput/gmao_oceanObs.nc
  test/testoutput/hgodas_adt.nc
  test/testoutput/rads_adt.nc
Labels: OBS3, Sprint

#900 Update the SatWinds AMV (from SSEC) ascii2ioda convert to follow JEDI Data Conventions
  src/conventional/CMakeLists.txt
  src/conventional/amv_ssec_ascii2ioda.py
  test/CMakeLists.txt
  test/testoutput/satwinds_ssec2021080103.nc
Labels: OBS3, Sprint

#867 Update gsidiag converter conventional data and satellite winds to comply with JEDI data convention
  src/gsi-ncdiag/gsi_ncdiag.py
  test/testoutput/satwind_obs_2018041500.nc4
  test/testoutput/satwinds_ssec2021080103.nc
  test/testoutput/sfc_tv_obs_2018041500.nc4
Labels: needs review

#918 Update 9 km SMAP soil moisture converter
  src/land/smap9km_ssm2ioda.py
  test/testoutput/smap9km_ssm.nc
Labels: Epic, needs review, OBS3, LAND

#926 Bugfix/ascii satwind datetime fix for SPRINT
  src/conventional/amv_ssec_ascii2ioda.py
  test/testoutput/satwinds_ssec2021080103.nc
Labels: needs review
