Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-10, with the labels that each got.

#1070 Obs error fix
  src/gsi-ncdiag/gsi_ncdiag.py
Labels: needs review

#1075 Adding soil depth to two smap ioda converters
  README.md
  src/land/smap9km_ssm2ioda.py
  src/land/smap_ssm2ioda.py
  test/CMakeLists.txt
  test/testoutput/smap9km_ssm.nc
  test/testoutput/smap_ssm.nc
Labels: OBS, LAND, AOP22

#1091 Using a best guesstimate of launch time, height, and wind components, estimate the lat/lon of a drifting radiosonde
  share/raob_stations.json
  src/conventional/sonde_tac2ioda.py
  test/testoutput/2021081612_sonde_small.nc
Labels: OBS
