Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-08, with the labels that each got.

#1015 Add ability to capture useful radiosonde QC info
  src/conventional/decode_bufr_LDM_raob.py
  test/testoutput/wmo_raob_double.nc4
Labels: OBS

#1021 A fix for SYNOP data containing BUFR subsets
  src/conventional/synop_bufr2ioda.py
  test/testoutput/synop_wmo_multi2.nc
Labels: OBS

#1027 Fix combine obsspace bug
  src/gsi-ncdiag/combine_obsspace.py
Labels: needs review

#1011 Modified tests for MacOS SIP compatibility.
  test/CMakeLists.txt
Labels: bug, OBS
