Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-01, with the labels that each got.

#688 GSI ncdiag converter for IODAv2
  src/gsi-ncdiag/CMakeLists.txt
  src/gsi-ncdiag/README.md
  src/gsi-ncdiag/combine_obsspace.py
  src/gsi-ncdiag/gsi_ncdiag.py
  src/gsi-ncdiag/proc_gsi_ncdiag.py
  src/gsi-ncdiag/subset_files.py
  src/lib-python/ioda_conv_engines.py
  test/CMakeLists.txt
  test/testoutput/amsua_aqua_obs_2018041500.nc4
  test/testoutput/satwind_obs_2018041500.nc4
  test/testoutput/sfc_tv_obs_2018041500.nc4
Labels: OBS3

#737 Update WMO BUFR format data and YAML files from single to multiple reports
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp
  src/bufr/DataObject/ArrayDataObject.cpp
  test/CMakeLists.txt
  test/testinput/amdar_wmoBUFR2ioda.yaml
  test/testinput/amdar_wmo_multi.bufr
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_15
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_16
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_17
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_18
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_19
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_21
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_23
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_25
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_26
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_27
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_28
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_30
  test/testinput/bufr_tables/bufrtab.TableB_STD_0_32
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_15
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_16
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_17
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_18
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_19
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_21
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_23
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_25
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_26
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_27
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_28
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_30
  test/testinput/bufr_tables/bufrtab.TableD_STD_0_32
  test/testinput/buoy_wmoBUFR2ioda.yaml
  test/testinput/buoy_wmo_multi.bufr
  test/testinput/ship_wmoBUFR2ioda.yaml
  test/testinput/ship_wmo_multi.bufr
  test/testinput/synop_wmoBUFR2ioda.yaml
  test/testinput/synop_wmo_multi.bufr
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/airep_multi.nc
  test/testoutput/amdar_wmo_multi.nc
  test/testoutput/bufr_read_2_dim_blocks.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/buoy_wmo_multi.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/gnssro_2020-306-2358C2E6.nc
  test/testoutput/satwind_EUMet.nc
  test/testoutput/satwind_Himawari.nc
  test/testoutput/ship_wmo_multi.nc
  test/testoutput/synop_wmo_multi.nc
Labels: OBS3

#743 Fix for norms under the feature/generic-bufr-LDM-raob-decode branch
  src/conventional/decode_bufr_LDM_raob.py
Labels: needs review, OBS3

#719 Feature/generic gnss ro decoder to ioda
  src/gnssro/CMakeLists.txt
  src/gnssro/gnssro_bufr2ioda.py
  test/CMakeLists.txt
  test/testinput/bfrPrf_C2E3.2020.349.21.26.R18_0001.0001_bufr
  test/testoutput/gnssro_cosmic2_2020121500.nc4
Labels: needs review, OBS3

#742 Bugfix for multiple input files in TROPOMI converter
  src/chem/tropomi_no2_nc2ioda.py
Labels: needs review, OBS3, COMPO

#734 IODA2 converter for concatenated raob BUFR data from LDM server
  .gitattributes
  src/bufr/CMakeLists.txt
  src/conventional/CMakeLists.txt
  src/conventional/decode_bufr_LDM_raob.py
  src/satbias/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/2021080100.radiosonde.BUFR
  test/testinput/2021112212.radiosonde.BUFR
  test/testinput/sonde_wmo_double.bufr
  test/testoutput/wmo_raob_double.nc4
  test/testoutput/wmo_raob_quadruple.nc4
Labels: needs review, OBS3

#746 add non-nominal check for processing near real time files
  src/gnssro/gnssro_bufr2ioda.py
Labels: OBS1

#706 Feature/argo2ioda v2
  src/marine/argoClim2ioda.py
  test/CMakeLists.txt
  test/testoutput/argoclim.nc
Labels: SOCA2

#761 Switch from using string-format datetime variable to the newer dateTime (seconds since epoch) in bufr2ioda.x application
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp
  src/bufr/BufrParser/Exports/Variables/DatetimeVariable.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject/Int64VecDataObject.cpp
  src/bufr/DataObject/Int64VecDataObject.h
  src/bufr/README.md
  test/testinput/aircar_BUFR2ioda.yaml
  test/testinput/airep_wmoBUFR2ioda.yaml
  test/testinput/amdar_wmoBUFR2ioda.yaml
  test/testinput/bufr_adpsfc.yaml
  test/testinput/bufr_airs_v2.yaml
  test/testinput/bufr_amsua_v2.yaml
  test/testinput/bufr_atms_v2.yaml
  test/testinput/bufr_avhrr_v2.yaml
  test/testinput/bufr_cris_v2.yaml
  test/testinput/bufr_filter_split.yaml
  test/testinput/bufr_filtering.yaml
  test/testinput/bufr_hirs_v2.yaml
  test/testinput/bufr_hrs.yaml
  test/testinput/bufr_mhs.yaml
  test/testinput/bufr_mhs_v2.yaml
  test/testinput/bufr_satwnd_new_format.yaml
  test/testinput/bufr_satwnd_old_format.yaml
  test/testinput/bufr_sevcrs_v2.yaml
  test/testinput/bufr_snow_adpsfc.yaml
  test/testinput/bufr_splitting.yaml
  test/testinput/bufr_ssmis_v2.yaml
  test/testinput/buoy_wmoBUFR2ioda.yaml
  test/testinput/gnssro_wmoBUFR2ioda.yaml
  test/testinput/satwind_EUMet_wmoBUFR2ioda.yaml
  test/testinput/satwind_Himawari_wmoBUFR2ioda.yaml
  test/testinput/ship_wmoBUFR2ioda.yaml
  test/testinput/synop_wmoBUFR2ioda.yaml
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/airep_multi.nc
  test/testoutput/amdar_wmo_multi.nc
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/buoy_wmo_multi.nc
  test/testoutput/gdas.aircar.t00z.20210801.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t06z.adpsfc.tm00.nc
  test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.seven.split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.filtering.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/gnssro_2020-306-2358C2E6.nc
  test/testoutput/satwind_EUMet.nc
  test/testoutput/satwind_Himawari.nc
  test/testoutput/ship_wmo_multi.nc
  test/testoutput/synop_wmo_multi.nc
Labels: OBS3

#762 Feature/add multithread to gnss ro converter
  src/gnssro/gnssro_bufr2ioda.py
Labels: OBS3
