Repository JCSDA-internal/ioda-converters, pull requests merged in 2022-02, with the labels that each got.

#775 Switch string datetime to int64 dateTime and reference Epoch (unix_time)
  src/conventional/metar_csv2ioda.py
  test/testoutput/2020100106_metars_small.nc
Labels: needs review, OBS3

#777 Feature/gnssro converter fillvalue
  src/gnssro/gnssro_bufr2ioda.f90
  test/testoutput/gnssro_kompsat5_2018041500.nc4
Labels: draft, needs review

#778 Feature/gnssro fortran ncdiag2ioda2
  src/gnssro/README
  src/gnssro/gnssro_bufr2ioda.f90
  src/gnssro/gnssro_gsidiag2ioda.f90
Labels: draft, needs review

#776 Add BUFR-2-IODA conversion of WMO BUFR-formatted RASS and VAD-winds data
  doc/bufr_obs_samples/rass_bufr_sample.txt
  doc/bufr_obs_samples/vadwinds_bufr_sample.txt
  doc/bufr_table_samples/rass_bufr_mnemonics.txt
  doc/bufr_table_samples/vadwinds_bufr_mnemonics.txt
  test/CMakeLists.txt
  test/testinput/rass_wmoBUFR2ioda.yaml
  test/testinput/rass_wmo_multi.bufr
  test/testinput/vadwinds_wmoBUFR2ioda.yaml
  test/testinput/vadwinds_wmo_multi.bufr
  test/testoutput/rass_wmo_multi.nc
  test/testoutput/vadwinds_wmo_multi.nc
Labels: needs review, OBS3

#780 Fix for the valid_range attribute definition in GNSSRO converters
  src/gnssro/gnssro_bufr2ioda.f90
  src/gnssro/gnssro_gsidiag2ioda.f90
  src/ncar-bufr2nc-fortran/gnssro_mod.f90
  test/testoutput/gnssro_kompsat5_2018041500.nc4
  test/testoutput/gnssro_obs_2018041500.nc4
Labels: needs review, OBS3

#782 Add converter for SatWinds WMO-formatted BUFR for INSAT and Aqua/Terra
  doc/bufr_obs_samples/satwinds_WMO_Insat_sample.txt
  doc/bufr_table_samples/satwinds_WMO_Insat_mnemonics.txt
  test/CMakeLists.txt
  test/testinput/satwind_Insat_wmo.bufr
  test/testinput/satwind_Insat_wmoBUFR2ioda.yaml
  test/testoutput/satwind_Insat.nc
Labels: OBS3

#689 Upgrade viirs_aod2ioda.py to version 2.
  src/chem/viirs_aod2ioda.py
  test/CMakeLists.txt
  test/testoutput/viirs_aod.nc
Labels: COMPO

#785 obs_absolute_dynamic_topography to absolute_dynamic_topography
  src/marine/copernicus_l4adt2ioda.py
  src/marine/gmao_obs2ioda.py
  src/marine/hgodas_adt2ioda.py
  src/marine/rads_adt2ioda.py
  test/testinput/hgodas_adt.nc
  test/testoutput/hgodas_adt.nc
  test/testoutput/ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc
  test/testoutput/rads_adt.nc
Labels: coordinate merge

#795 In order for these bufr2ioda converters to work in UFO, there must be a height variable.
  test/testinput/buoy_wmoBUFR2ioda.yaml
  test/testinput/ship_wmoBUFR2ioda.yaml
  test/testinput/synop_wmoBUFR2ioda.yaml
  test/testoutput/buoy_wmo_multi.nc
  test/testoutput/ship_wmo_multi.nc
  test/testoutput/synop_wmo_multi.nc
Labels: OBS3

#798 add cleaner exit using curl to check for file on server
  tools/ingest/retrieve_data_from_noaa_nomads.sh
Labels: OBS1, OBS3

#796 Feature/v2 smap9km
  src/land/CMakeLists.txt
  src/land/smap9km_ssm2ioda.py
  test/CMakeLists.txt
  test/testinput/SMAP_L2_SM_P_E_36365_D_20211122T013945_R18240_001.h5
  test/testoutput/smap9km_ssm.nc
Labels: enhancement, Epic, needs review, OBS3, LAND

#801 Add quick method to return metagroup name
  src/lib-python/ioda_conv_engines.py
Labels: OBS3
