Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-07, with the labels that each got.

#1256 Feature/nick e adpsfc sfcshp pythonapi
  test/CMakeLists.txt
  test/testinput/gdas.t00z.sfcshp.prepbufr
  test/testinput/prepbufr_adpsfc_api.py
  test/testinput/prepbufr_sfcshp_api.py
  test/testoutput/prepbufr_adpsfc_api.nc
  test/testoutput/prepbufr_sfcshp_api.nc
Labels: enhancement, OBS

#1291 Update ATMS converter yaml for EWOK ingest suite
  test/testinput/bufr_ncep_atms_remap.yaml
  test/testinput/bufr_ncep_atms_ta_remap.yaml
Labels: needs review, INFRA

#1305 Fix for missing gsl-lite dependency
  CMakeLists.txt
  src/bufr/CMakeLists.txt
  tools/bufr/CMakeLists.txt
Labels: ready for merge

#1311 adding back in mopitt_co test and file
  test/CMakeLists.txt
  test/testinput/mopitt_co.he5
Labels: ready for merge

#1312 OMPS O3 TC converter for JCSDA ingest
  src/compo/CMakeLists.txt
  src/compo/omps_o3_nm_h52ioda.py
  test/CMakeLists.txt
  test/testinput/OMPS-NPP_NMTO3-L2_v2.1_2020m0903t162415_small.h5
  test/testinput/OMPS-NPP_NMTO3-L2_v2.1_2020m0903t180544_small.h5
  test/testoutput/omps_o3_nm.nc
Labels: ready for merge, COMPO
