Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-08, with the labels that each got.

#1290 CMake config update for NCEPLIBS-bufr v12.0
  src/bufr/BufrParser/Query/DataProvider/DataProvider.cpp
  src/bufr/BufrParser/Query/DataProvider/DataProvider.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.h
  src/gnssro/CMakeLists.txt
  src/ncar-bufr2nc-fortran/CMakeLists.txt
  test/testinput/prepbufr_adpsfc_api.py
  tools/bufr/CMakeLists.txt
  tools/fortran/CMakeLists.txt
Labels: OBS, INFRA, do not merge

#1321 Ioda-converters for the [3D]-RTMA ADPSFC data
  test/CMakeLists.txt
  test/testinput/bufr_ncep_rtma_adpsfc.yaml
  test/testinput/rtma_ru.t0000z.adpsfc_nc000101.tm00.bufr_d
  test/testoutput/rtma_ru.t0000z.adpsfc_nc000101.tm00.nc
Labels: OBS

#1287 Bugfix/sensor scan position integer
  src/bufr/BufrParser/Exports/Variables/SensorScanPositionVariable.cpp
  src/compo/omi_o3_nc2ioda.py
  src/compo/ompsnm_o3_nc2ioda.py
  src/goes/goes_converter.py
  src/gsi_ncdiag/gsi_ncdiag.py
  src/hdf5/amsr2_2ioda.py
  src/hdf5/atms_netcdf_hdf5_2ioda.py
  src/hdf5/cowvr_hdf5_2ioda.py
  src/hdf5/gmi_2ioda.py
  src/hdf5/tropics_2ioda.py
  test/testinput/bufr_ncep_1bamua_n15.yaml
  test/testinput/bufr_ncep_1bamua_ta.yaml
  test/testinput/bufr_ncep_atms.yaml
  test/testinput/bufr_ncep_atms_remap.yaml
  test/testinput/bufr_ncep_atms_ta_remap.yaml
  test/testinput/bufr_ncep_ssmis.yaml
  test/testoutput/2018041500_atms_BGRemap_sdr.nc4
  test/testoutput/2021120600_atms_sdr.nc4
  test/testoutput/amsua_aqua_obs_2018041500.nc4
  test/testoutput/gdas.t00z.atms_n20.tm00.nc
  test/testoutput/gdas.t12z.amsua_metop-c_ta.tm00.nc
  test/testoutput/gdas.t12z.amsua_n15.tm00.nc
  test/testoutput/gdas.t12z.mtiasi_metop-c.tm00.nc
  test/testoutput/omi_o3_l2.nc
  test/testoutput/ompsnm_o3_l2.nc
Labels: coordinate merge, OBS

#1323 Change Ozone Variable Name and Turn on Error
  src/gsi_ncdiag/gsi_ncdiag.py
  test/testoutput/amsua_aqua_obs_2018041500.nc4
Labels: ready for merge, OBS

#1329 Update README.md
  src/ncar-bufr2nc-fortran/README.md
Labels: OBS

#1331 update number of channels and frequencies
  src/hdf5/gmi_2ioda.py
Labels: OBS, do not merge

#1334 bug fix to make QCPath values out of 0 to 31 valid
  src/compo/viirs_aod2ioda.py
  test/testoutput/viirs_aod.nc
Labels: bug, OBS

#1338 Bugfix/unify kinds
  src/CMakeLists.txt
  src/bufr/BufrParser/Exports/Variables/Transforms/atms/atms_spatial_average_mod.f90
  src/bufr/BufrParser/Exports/Variables/Transforms/atms/kinds.F90
  src/bufr/CMakeLists.txt
  src/ncar-bufr2nc-fortran/CMakeLists.txt
  src/ncar-bufr2nc-fortran/define_mod.f90
  src/ncar-bufr2nc-fortran/hsd.f90
  src/ncar-bufr2nc-fortran/main.f90
  src/ncar-bufr2nc-fortran/ncio_mod.f90
  src/ncar-bufr2nc-fortran/prepbufr_mod.f90
  src/ncar-bufr2nc-fortran/radiance_mod.f90
  src/ncar-bufr2nc-fortran/satwnd_mod.f90
  src/ncar-bufr2nc-fortran/utils_mod.f90
  src/utils/CMakeLists.txt
  src/utils/iodaconv_kinds.f90
Labels: OBS

#1335 Without this the code does not compile
  src/CMakeLists.txt
  src/bufr/BufrParser/Exports/Variables/Transforms/atms/atms_spatial_average_mod.f90
  src/bufr/BufrParser/Exports/Variables/Transforms/atms/kinds.F90
  src/bufr/CMakeLists.txt
  src/ncar-bufr2nc-fortran/CMakeLists.txt
  src/ncar-bufr2nc-fortran/define_mod.f90
  src/ncar-bufr2nc-fortran/hsd.f90
  src/ncar-bufr2nc-fortran/main.f90
  src/ncar-bufr2nc-fortran/ncio_mod.f90
  src/ncar-bufr2nc-fortran/prepbufr_mod.f90
  src/ncar-bufr2nc-fortran/radiance_mod.f90
  src/ncar-bufr2nc-fortran/satwnd_mod.f90
  src/ncar-bufr2nc-fortran/utils_mod.f90
  src/utils/CMakeLists.txt
  src/utils/iodaconv_kinds.f90
Labels: bug, OBS

#1333 fix channel number for amsr2
  src/hdf5/amsr2_2ioda.py
Labels: OBS

#1343 tropics converter update for libs
  src/gnssro/gnssro_bufr2ioda.py
  src/hdf5/atms_netcdf_hdf5_2ioda.py
  src/hdf5/tropics_2ioda.py
  src/pyiodaconv/def_jedi_utils.py
Labels: OBS

#1347 Adusting the verbosite flag check used by `tools/iodaconv_comp.sh`
  test/CMakeLists.txt
  tools/iodaconv_comp.sh
Labels: OBS

#1339 Adding ctest for the new gmi converter
  src/hdf5/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/gmi_gpm_20220216.h5
  test/testoutput/gmi_gpm_20220216.nc4
Labels: OBS

#1340 Adding ctest for the new amsr2_gcom-w1 converter
  src/hdf5/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/amsr2_gcom-w1_20220216.h5
  test/testoutput/amsr2_gcom-w1_20220216.nc4
Labels: OBS
