Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-01, with the labels that each got.

#1121 Sprint: Updating two GOES and three marine converters for naming conventions
  src/compo/mls_o3_nc2ioda.py
  src/compo/modis_aod2ioda.py
  src/compo/mopitt_co_nc2ioda.py
  src/compo/omi_o3_nc2ioda.py
  src/compo/ompsnm_o3_nc2ioda.py
  src/gnssro/gnssro_bufr2ioda.py
  src/goes/goes.py
  src/goes/goes_converter.py
  src/goes/goes_latlon.py
  src/land/smap9km_ssm2ioda.py
  src/land/smap_ssm2ioda.py
  src/lib-python/orddicts.py
  src/marine/amsr2_icec2ioda.py
  src/marine/avhrr_radiance2ioda.py
  src/marine/copernicus_l3swh2ioda.py
  src/marine/copernicus_l4adt2ioda.py
  src/marine/nsidc_l4cdr_ice2ioda.py
  src/marine/pace_oc2ioda.py
  src/marine/pace_radiance2ioda.py
  src/marine/smap_sss2ioda.py
  src/marine/smos_sss2ioda.py
  src/marine/viirs_modis_l2_oc2ioda.py
  src/marine/viirs_modis_l3_oc2ioda.py
  test/CMakeLists.txt
  test/testoutput/amsr2_icec_l2p.nc
  test/testoutput/amsua_aqua_obs_2018041500.nc4
  test/testoutput/avhrr_radiance.nc
  test/testoutput/gnssro_cosmic2_2021080212.nc4
  test/testoutput/ioda_dt_global_twosat_phy_l4_20190101_vDT2021.nc
  test/testoutput/ioda_global_vavh_l3_rt_s3a_20210930T18.nc
  test/testoutput/mls_o3_l2.nc
  test/testoutput/modis_aod.nc
  test/testoutput/modis_aqua_oc_l2.nc
  test/testoutput/mopitt_co.nc
  test/testoutput/nsidc_l4_icec.nc
  test/testoutput/omi_o3_l2.nc
  test/testoutput/ompsnm_o3_l2.nc
  test/testoutput/pace_oc_l2.nc
  test/testoutput/pace_radiance_L1B.nc
  test/testoutput/smap9km_ssm.nc
  test/testoutput/smap_ssm.nc
  test/testoutput/smap_sss_rss.nc
  test/testoutput/smos_sss_l2.nc
  test/testoutput/viirs_jpss1_oc_l2.nc
  test/testoutput/viirs_jpss1_oc_l3.nc
Labels: OBS, Sprint

#1089 Update GPS platforms and group GNSSRO data referring to "record_number".
  src/gsi-ncdiag/gsi_ncdiag.py
  test/testoutput/satwind_obs_2018041500.nc4
Labels: JEDI-GEOS, AOP22

#1138 Update the sprint branch again with develop changes mostly for BUFR (via PR1100)
  src/compo/airnow2ioda-nc.py
  src/compo/mls_o3_nc2ioda.py
  src/compo/omi_o3_nc2ioda.py
  src/compo/ompsnm_o3_nc2ioda.py
  src/compo/tropomi_no2_co_nc2ioda.py
  src/conventional/sonde_tac2ioda.py
  src/gnssro/gnssro_bufr2ioda.py
  src/gsi-ncdiag/gsi_ncdiag.py
  src/land/smap9km_ssm2ioda.py
  src/marine/amsr2_icec2ioda.py
  src/marine/ostia_l4sst2ioda.py
  src/marine/pace_oc2ioda.py
  src/marine/pace_radiance2ioda.py
  src/marine/swot_l2adt2ioda.py
  src/marine/viirs_modis_l2_oc2ioda.py
  test/CMakeLists.txt
  test/testinput/adpupa_prepbufr.yaml
  test/testinput/bufr_empty_fields.yaml
  test/testinput/bufr_filter_split.yaml
  test/testinput/bufr_hrs.yaml
  test/testinput/bufr_mhs.yaml
  test/testinput/bufr_simple_groupby.yaml
  test/testinput/gdas.t12z.adpupa.tm00.bufr_d
  test/testoutput/2021081612_sonde_small.nc
  test/testoutput/SWOT_L2_ADT.nc
  test/testoutput/adpupa_prepbufr.nc
  test/testoutput/adpupa_prepbufr_group_by.nc
  test/testoutput/airnow_2020081306.nc
  test/testoutput/amsr2_icec_l2p.nc
  test/testoutput/aod_viirs_obs_2018041500_s.nc4
  test/testoutput/bufr_empty_fields.nc
  test/testoutput/bufr_simple_groupby.nc
  test/testoutput/gdas.t00z.1bhrs4.tm00.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.15.7.filter_split.nc
  test/testoutput/gdas.t18z.1bmhs.tm00.nc
  test/testoutput/gnssro_cosmic2_2021080212.nc4
  test/testoutput/mls_o3_l2.nc
  test/testoutput/modis_aqua_oc_l2.nc
  test/testoutput/omi_o3_l2.nc
  test/testoutput/ompsnm_o3_l2.nc
  test/testoutput/pace_oc_l2.nc
  test/testoutput/pace_radiance_L1B.nc
  test/testoutput/smap9km_ssm.nc
  test/testoutput/sst_ostia.nc
  test/testoutput/tropomi_co_total.nc
  test/testoutput/tropomi_no2_total.nc
  test/testoutput/tropomi_no2_tropo.nc
  test/testoutput/viirs_jpss1_oc_l2.nc
Labels: OBS, Sprint

#1141 Fix a collection of bufr2ioda.x YAML files and test-ref files for naming conventions
  src/bufr/BufrParser/Exports/Variables/AircraftAltitudeVariable.cpp
  src/compo/tropomi_no2_co_nc2ioda.py
  src/conventional/sonde_bufr2ioda.py
  src/gsi-ncdiag/gsi_ncdiag.py
  test/CMakeLists.txt
  test/testinput/bufr_ncep_aircft_AMDAR103.yaml
  test/testinput/bufr_ncep_aircft_noAMDAR103.yaml
  test/testinput/bufr_ncep_sevcsr.yaml
  test/testinput/bufr_read_wmo_radiosonde.yaml
  test/testinput/bufr_satwnd_new_format.yaml
  test/testinput/bufr_satwnd_old_format.yaml
  test/testinput/bufr_wmo_amdar_multi.yaml
  test/testinput/sonde_wmo_double.bufr
  test/testoutput/NC005031.nc
  test/testoutput/NC005066.nc
  test/testoutput/amsua_aqua_obs_2018041500.nc4
  test/testoutput/bufr_read_wmo_radiosonde.nc
  test/testoutput/bufr_wmo_amdar_multi.nc
  test/testoutput/gdas.t00z.sevcsr.tm00.nc
  test/testoutput/gdas.t12z.aircft_AMDAR103.tm00.nc
  test/testoutput/gdas.t12z.aircft_noAMDAR103.tm00.nc
  test/testoutput/satwind_obs_2018041500.nc4
  test/testoutput/sfc_tv_obs_2018041500.nc4
  test/testoutput/wmo_raob_double.nc4
Labels: coordinate merge, OBS

#1111 Add the capability of converting scaled radiance to radinace for Hype…
  src/bufr/BufrParser/BufrParser.cpp
  src/bufr/BufrParser/Exports/Export.cpp
  src/bufr/BufrParser/Exports/Variables/SpectralRadianceVariable.cpp
  src/bufr/BufrParser/Exports/Variables/SpectralRadianceVariable.h
  src/bufr/CMakeLists.txt
  test/testinput/bufr_ncep_mtiasi.yaml
  test/testoutput/gdas.t12z.mtiasi.metop-c.tm00.nc
Labels: ready for merge

#1076 Work on regional cloud-related yamlfiles for adpsfc prepbufr and lgycld bufr data
  test/CMakeLists.txt
  test/testinput/bufr_ncep_lgycld_rrfs.yaml
  test/testinput/bufr_ncep_prepbufr_adpsfc_cloud_rrfs.yaml
  test/testinput/rap.t06z.adpsfc.prepbufr.tm00
  test/testinput/rap.t06z.lgycld.tm00.bufr_d
  test/testoutput/rrfs.t06z.adpsfc.prepbufr.nc
  test/testoutput/rrfs.t06z.lgycld.bufr.nc
Labels: needs review, OBS, AOP22

#1147 Radiosonde legacy/text (TAC) bugfix for knots vs m/s based on day-of-month coding per WMO manual on codes
  src/conventional/sonde_tac2ioda.py
  test/testoutput/2021081612_sonde_small.nc
Labels: OBS

#1149 Radiosondes: BUFR incoming data (from LDM), skip duplicates
  src/conventional/sonde_bufr2ioda.py
  test/testoutput/wmo_raob_double.nc4
Labels: OBS

#1148 Bugfix: launch hour can be inconsistent across the globe
  src/conventional/sonde_tac2ioda.py
  src/lib-python/meteo_sounding_utils.py
  test/CMakeLists.txt
  test/testoutput/2021081612_sonde_small.nc
Labels: OBS

#1151 Bugfix: found times when converters crashed when testing with dozens of input files
  src/conventional/sonde_bufr2ioda.py
  src/conventional/sonde_tac2ioda.py
  src/lib-python/meteo_sounding_utils.py
  test/testoutput/2021081612_sonde_small.nc
  test/testoutput/wmo_raob_double.nc4
Labels: OBS

#1153 BUGFIX: incoming SSEC AMV data has wrong convention for east/western hemispheres
  src/conventional/amv_ssec_ascii2ioda.py
  test/testoutput/satwinds_ssec2021080103.nc
Labels: OBS

#1155 fixed the bug #1154 for tropomi_no2_co_nc2ioda.py
  src/compo/tropomi_no2_co_nc2ioda.py
Labels: bug, COMPO
