Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-10, with the labels that each got.

#1381 Set minimum version for NCEPLIB-bufr
  CMakeLists.txt
  src/CMakeLists.txt
  src/bufr/CMakeLists.txt
  test/CMakeLists.txt
  tools/CMakeLists.txt
  tools/fortran/CMakeLists.txt
  tools/run_satwnds/CMakeLists.txt
Labels: OBS, INFRA

#1387 renaming test input and output files AMSR2 iodaconv ctest
  test/CMakeLists.txt
  test/testinput/sample.amsr2.gcom-w1.20220216.h5
  test/testoutput/20220216T00Z_PT1H_amsr2_sample.nc4
Labels: OBS

#1390 Ioda-converters for the [3D]-RTMA AIRCFT data
  test/CMakeLists.txt
  test/testinput/bufr_ncep_rtma_aircft.yaml
  test/testinput/bufr_ncep_rtma_aircft_NC004103.yaml
  test/testinput/rtma_ru.t0000z.aircft.tm00_nc004006.bufr_d
  test/testinput/rtma_ru.t0000z.aircft.tm00_nc004103.bufr_d
  test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004006.nc
  test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004103.nc
Labels: OBS

#1394 Add option to save LSW in gnssro bufr2ioda
  src/gnssro/gnssro_bufr2ioda.py
Labels: OBS

#1395 Fixed fault with unintialized file unit variable.
  src/obserror/obserror2ioda.f90
Labels: OBS, INFRA

#1392 Set a consistent, non-zero tolerance for comparing floating point values
  test/CMakeLists.txt
Labels: OBS, INFRA

#1397 Fixed overflow issues with int64 fill value handling
  test/testinput/bufr_ncep_prepbufr_adpupa.py
  test/testinput/prepbufr_adpsfc_api.py
  test/testinput/prepbufr_sfcshp_api.py
  test/testoutput/prepbufr_adpsfc_api.nc
  test/testoutput/prepbufr_adpupa_api.nc
  test/testoutput/prepbufr_sfcshp_api.nc
Labels: OBS, INFRA

#1400 Replace input & output ATMS ctest files to update date
  test/CMakeLists.txt
  test/testinput/SNDR.J1.ATMS.20180415T0000.nc4
  test/testinput/SNDR_SNPP_ATMS_SAMPLE.nc4
  test/testinput/sample.SNDR.J1.ATMS.2022021600.nc4
  test/testinput/sample.SNDR.SNPP.ATMS.2022021600.nc4
  test/testoutput/2018041500_atms_BGRemap_sdr.nc4
  test/testoutput/2021120600_atms_sdr.nc4
  test/testoutput/2022021600_atms_BGRemap_sdr.nc4
  test/testoutput/2022021600_atms_sdr.nc4
Labels: needs review, OBS

#1399 Fix crash with bufr2nc_fortran.x on macOS
  src/ncar-bufr2nc-fortran/hsd.f90
  src/ncar-bufr2nc-fortran/ncio_mod.f90
Labels: OBS, INFRA

#1405 fix for compiler flags
  cmake/compiler_flags_GNU_Fortran.cmake
Labels: needs review, OBS

#1301 New converter for MRMS (multi-radar, multi-sensor) radar reflectivity over CONUS (continental U.S.)
  CI/buildspec_clang.yml
  CI/buildspec_gnu.yml
  CI/buildspec_intel.yml
  src/CMakeLists.txt
  src/mrms/CMakeLists.txt
  src/mrms/mrms_grib2ioda.py
  test/CMakeLists.txt
  test/testinput/MRMS_MergedReflectivityQC_01.50_20230712-152241.grib2
  test/testoutput/mrms_reflectivity_Z1500m.nc
Labels: ready for merge, OBS
