Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-09, with the labels that each got.

#1350 bug fixes for the tempo converter
  src/compo/tempo_nc2ioda.py
Labels: COMPO

#1352 Refactor the bottle neck in combining the geovals
  src/gsi_ncdiag/combine_obsspace.py
Labels: ready for merge

#1355 tropics converter update
  src/hdf5/tropics_2ioda.py
Labels: OBS

#1363 Split Pibal from Sondes
  src/gsi_ncdiag/gsi_ncdiag.py
Labels: OBS, NASA

#1362 Make the saturation specific humidity names consistent with UFO code and test files
  src/gsi_ncdiag/gsi_ncdiag.py
Labels: OBS, NASA

#1358 Adding ctest for the updated TROPICS converter
  src/hdf5/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/TROPICS01.L1B.V03-04.ST20220216-012443.ET20220216-025955.nc
  test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4
Labels: OBS

#1356 Add aircraft bias converter
  CMakeLists.txt
  src/CMakeLists.txt
  src/gsi_varbc/CMakeLists.txt
  src/gsi_varbc/CPPLINT.cfg
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  src/gsi_varbc/GsiAircraftBiasReader.cc
  src/gsi_varbc/GsiAircraftBiasReader.h
  src/gsi_varbc/GsiSatBiasReader.cpp
  src/gsi_varbc/GsiSatBiasReader.h
  src/gsi_varbc/README.md
  src/gsi_varbc/SatBiasConverter.cpp
  src/gsi_varbc/generate_aircraft_bias_csv.py
  src/gsi_varbc/satbias_upgrader.py
  test/CMakeLists.txt
  test/testinput/acftbias_converter.yaml
  test/testoutput/varbc/acft_out.nc4
Labels: OBS, code sprint

#1360 satellite bias coefficient conversion update including upgrader
  CMakeLists.txt
  src/CMakeLists.txt
  src/compo/viirs_biaswriter.py
  src/gsi_varbc/CMakeLists.txt
  src/gsi_varbc/CPPLINT.cfg
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  src/gsi_varbc/GsiAircraftBiasReader.cc
  src/gsi_varbc/GsiAircraftBiasReader.h
  src/gsi_varbc/GsiSatBiasReader.cpp
  src/gsi_varbc/GsiSatBiasReader.h
  src/gsi_varbc/README.md
  src/gsi_varbc/SatBiasConverter.cpp
  src/gsi_varbc/generate_aircraft_bias_csv.py
  src/gsi_varbc/satbias_upgrader.py
  src/satbias/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/acftbias_converter.yaml
  test/testinput/satbias_converter_amsua.yaml
  test/testinput/satbias_converter_cris.yaml
  test/testinput/satbias_converter_gmi_gpm.yaml
  test/testinput/satbias_converter_ssmis.yaml
  test/testoutput/satbias_amsua_n18.nc4
  test/testoutput/satbias_cris_npp.nc4
  test/testoutput/satbias_gmi_gpm.nc4
  test/testoutput/satbias_ssmis_f16.nc4
  test/testoutput/varbc/acft_out.nc4
  test/testoutput/varbc/satbias_amsua_n18.nc4
  test/testoutput/varbc/satbias_cris_npp.nc4
  test/testoutput/varbc/satbias_gmi_gpm.nc4
  test/testoutput/varbc/satbias_ssmis_f16.nc4
  test/testoutput/varbc/viirs_bias.nc
  test/testoutput/viirs_bias.nc
Labels: OBS, code sprint

#1368 Bugfix/mcmodel fix
  cmake/iodaconv_compiler_flags.cmake
Labels: ready for merge, OBS

#1328 Hotfix to add releaseTime to adpupa converter
  test/testinput/bufr_ncep_prepbufr_adpupa.py
  test/testoutput/prepbufr_adpupa_api.nc
Labels: OBS

#1367 replacing test files with smaller data case
  test/testinput/gmi_gpm_20220216.h5
  test/testoutput/gmi_gpm_20220216.nc4
Labels: OBS

#1365 obs2ioda cris and iasi update
  src/ncar-bufr2nc-fortran/define_mod.f90
  src/ncar-bufr2nc-fortran/radiance_mod.f90
Labels: OBS

#1369 Add lastUpdateTime to aircraft VarBC files
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  test/testoutput/varbc/acft_out.nc4
Labels: OBS, code sprint, NWS

#1372 COWVR converter to also decode EDR
  src/hdf5/cowvr_hdf5_2ioda.py
Labels: OBS, INGEST

#1375 replacing tropics ctest files with smaller data case
  test/CMakeLists.txt
  test/testinput/TROPICS01.L1B.V03-04.ST20220216-012443.ET20220216-025955.nc
  test/testinput/tropics_2022021600.nc
  test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4
Labels: OBS

#1221 Refactored QueryRunner::collectData
  doc/bufr_uml/DataCollection.png
  doc/bufr_uml/DataCollection.puml
  doc/bufr_uml/QueryClassDiagram.png
  doc/bufr_uml/QueryClassDiagram.puml
  src/bufr/BufrParser/Query/DataProvider/DataProvider.h
  src/bufr/BufrParser/Query/DataProvider/NcepDataProvider.cpp
  src/bufr/BufrParser/Query/DataProvider/WmoDataProvider.cpp
  src/bufr/BufrParser/Query/NodeLookupTable.cpp
  src/bufr/BufrParser/Query/NodeLookupTable.h
  src/bufr/BufrParser/Query/QueryRunner.cpp
  src/bufr/BufrParser/Query/QueryRunner.h
  src/bufr/BufrParser/Query/SubsetTable.cpp
  src/bufr/BufrParser/Query/SubsetTable.h
  src/bufr/BufrParser/Query/Target.h
  src/bufr/CMakeLists.txt
  test/testinput/bufr_ncep_adpsfc.yaml
  test/testinput/bufr_ncep_nbd_snow2.txt
Labels: enhancement, waiting for other repos, OBS, INFRA, NWS
