Repository JCSDA-internal/ioda-converters, pull requests merged in 2023-11, with the labels that each got.

#1407 Add a new variable for the wigosid to the bufr2ioda code(s): new
  src/bufr/BufrParser/Exports/Export.cpp
  src/bufr/BufrParser/Exports/Variables/WigosidVariable.cpp
  src/bufr/BufrParser/Exports/Variables/WigosidVariable.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.h
  test/testinput/bufr_ncep_rtma_adpsfc.yaml
  test/testoutput/rtma_ru.t0000z.adpsfc_nc000101.tm00.nc
Labels: OBS

#1411 ncdiag radiance bias addition to ioda output
  src/gsi_ncdiag/gsi_ncdiag.py
  src/gsi_ncdiag/ncdiag_to_feedback.py
  src/gsi_ncdiag/proc_gsi_ncdiag.py
  src/gsi_ncdiag/test_gsidiag.py
Labels: ready for merge, OBS

#1344 Feature/query new result
  src/bufr/BufrParser/Query/File.cpp
  src/bufr/BufrParser/Query/NodeLookupTable.cpp
  src/bufr/BufrParser/Query/QueryParser.h
  src/bufr/BufrParser/Query/QueryRunner.cpp
  src/bufr/BufrParser/Query/QueryRunner.h
  src/bufr/BufrParser/Query/QuerySet.cpp
  src/bufr/BufrParser/Query/ResultSet.cpp
  src/bufr/BufrParser/Query/ResultSet.h
  src/bufr/BufrParser/Query/SubsetLookupTable.cpp
  src/bufr/BufrParser/Query/SubsetLookupTable.h
  src/bufr/BufrParser/Query/Target.h
  src/bufr/BufrParser/Query/VectorMath.h
  src/bufr/CMakeLists.txt
  test/testinput/bufr_ncep_adpsfc.yaml
Labels: bug, enhancement, waiting for other repos, NWS

#1408 generic gnssro ncepbufr2ioda converter
  src/gnssro/CMakeLists.txt
  src/gnssro/README
  src/gnssro/gnssro_bufr2ioda.f90
  test/CMakeLists.txt
  test/testoutput/gnssro_obs_3prof_2022090100.nc4
Labels: ready for merge, OBS

#1401 Changes to converters for VarBC files
  src/compo/viirs_biaswriter.py
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  src/gsi_varbc/SatBiasConverter.cpp
  src/gsi_varbc/satbias_upgrader.py
  test/testinput/acftbias_converter.yaml
  test/testinput/satbias_converter.yaml
  test/testinput/satbias_converter_amsua.yaml
  test/testinput/satbias_converter_cris.yaml
  test/testinput/satbias_converter_gmi_gpm.yaml
  test/testinput/satbias_converter_ssmis.yaml
  test/testoutput/varbc/acft_out.nc4
  test/testoutput/varbc/satbias_amsua_n18.nc4
  test/testoutput/varbc/satbias_cris_npp.nc4
  test/testoutput/varbc/satbias_gmi_gpm.nc4
  test/testoutput/varbc/satbias_ssmis_f16.nc4
  test/testoutput/varbc/viirs_bias.nc
Labels: code sprint

#1325 BUFR query: Handle long strings from BUFR files
  CMakeLists.txt
  src/bufr/BufrParser/Query/Constants.h
  src/bufr/BufrParser/Query/Data.h
  src/bufr/BufrParser/Query/DataProvider/DataProvider.cpp
  src/bufr/BufrParser/Query/DataProvider/DataProvider.h
  src/bufr/BufrParser/Query/File.cpp
  src/bufr/BufrParser/Query/NodeLookupTable.cpp
  src/bufr/BufrParser/Query/QueryParser.h
  src/bufr/BufrParser/Query/QueryRunner.cpp
  src/bufr/BufrParser/Query/QueryRunner.h
  src/bufr/BufrParser/Query/QuerySet.cpp
  src/bufr/BufrParser/Query/ResultSet.cpp
  src/bufr/BufrParser/Query/ResultSet.h
  src/bufr/BufrParser/Query/SubsetLookupTable.cpp
  src/bufr/BufrParser/Query/SubsetLookupTable.h
  src/bufr/BufrParser/Query/SubsetTable.cpp
  src/bufr/BufrParser/Query/SubsetTable.h
  src/bufr/BufrParser/Query/Target.h
  src/bufr/BufrParser/Query/VectorMath.h
  src/bufr/CMakeLists.txt
  src/bufr/DataObject.h
  src/ncar-bufr2nc-fortran/CMakeLists.txt
  src/ncepbufr/bufr_ncep_prepbufr_adpupa.py
  test/CMakeLists.txt
  test/testinput/bufr_ncep_adpsfc.yaml
  test/testinput/bufr_ncep_aircft_AMDAR103.yaml
  test/testinput/bufr_ncep_long_strs.yaml
  test/testinput/bufr_query_python_test.py
  test/testinput/gdas.t06z.snocvr.tm00.bufr_d
  test/testoutput/bufr_ncep_long_strs.nc
Labels: enhancement, waiting for other repos, OBS, NWS

#1414 Pass TotalBias argument to Ozone.toGeovals
  src/gsi_ncdiag/gsi_ncdiag.py
Labels: ready for merge, OBS

#1420 comment out bad ctest for now
  test/CMakeLists.txt
Labels: OBS

#1419 Fix failing BUFR ctests.
  src/bufr/BufrParser/Exports/Variables/SensorScanAngleVariable.cpp
  src/bufr/BufrParser/Query/QuerySet.cpp
  src/bufr/BufrParser/Query/ResultSet.cpp
  test/CMakeLists.txt
  test/testinput/bufr_ncep_prepbufr_aircft.yaml
  test/testoutput/prepbufr_adpupa_api.nc
  test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004006.nc
  test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004103.nc
Labels: NWS
