Repository JCSDA-internal/ioda-converters, pull requests merged in 2024-08, with the labels that each got.

#1537 [Bug] fix thickness variable names for specified layers
  src/gsi_varbc/satbias_upgrader.py
Labels: OBS

#1538 [bugfix] Fix the timestamp for proper 4 digits (ignore seconds)
  src/mrms/mrms_grib2ioda.py
Labels: bug, OBS

#1528 GMAO Converter Update
  src/marine/gmao_obs2ioda.py
  test/CMakeLists.txt
  test/testinput/gmao-obs-20180415.nc
  test/testinput/gmao_argo.nc
  test/testoutput/gmao_argo.nc
  test/testoutput/gmao_oceanObs.nc
Labels: OBS, NASA
