Repository JCSDA-internal/ioda-converters, pull requests merged in 2024-11, with the labels that each got.

#1568 Feature/nicke air bc record variable
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  test/testoutput/acft_out.nc4
  test/testoutput/varbc/acft_out.nc4
Labels: coordinate merge, NWS

#1556 add computation of specificHumidity and add to output
  src/conventional/CMakeLists.txt
  src/conventional/balloon_sonde_json2ioda.py
  test/CMakeLists.txt
  test/testinput/balloonsonde_sample_20241001T00Z_PT15M.json
  test/testoutput/obs.20241001T000000Z_PT15M_balloonsonde.nc4
Labels: OBS

#1581 add a return if no data locations are found
  src/hdf5/tropics_2ioda.py
Labels: OBS

#1582 update WMO satellite IDs
  src/hdf5/tropics_2ioda.py
  test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4
Labels: OBS

#1584 adjust bit checking of quality word
  src/hdf5/tropics_2ioda.py
  test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4
Labels: needs review, OBS
