Repository JCSDA-internal/ioda-converters, pull requests merged in 2024-07, with the labels that each got.

#1529 add units for GNSS total electron content
  src/gnssro/gnss_tec_bufr2ioda.py
Labels: OBS, NAVY

#1530 icartt_nc converter for compo
  src/compo/CMakeLists.txt
  src/compo/icartt_nc2ioda.py
  test/CMakeLists.txt
  test/testinput/icartt_DC8_20230627_RA.nc
  test/testoutput/ioda_icartt_DC8_20230627_RA.nc
Labels: COMPO

#1499 initial commit of cloudsat decoder
  src/hdf5/CMakeLists.txt
  src/hdf5/cloudsat_netcdf_to_ioda.py
  src/hdf5/read_cloudsat.py
Labels: OBS, NASA

#1536 remove ims scf ctest no longer used
  CMakeLists.txt
  src/land/afwa_snod2ioda.py
  src/land/ims_scf2ioda.py
  test/CMakeLists.txt
Labels: OBS

#1527 first version of ionosonde decoder
  .pycodestyle
  src/conventional/CMakeLists.txt
  src/conventional/ionosonde_ascii2ioda.py
  test/CMakeLists.txt
  test/testinput/AL945_2020277203000.EDP
  test/testoutput/ionosonde_edp_20201003T203000Z.nc4
Labels: OBS, NAVY
