Repository JCSDA-internal/ioda-converters, pull requests merged in 2024-02, with the labels that each got.

#1449 augmenting OSW decoder for CYGNSS
  src/hdf5/cygnss_2ioda.py
Labels: OBS

#1447 augmenting OSW converter for Spire
  src/hdf5/spire_2ioda.py
Labels: OBS

#1454 Ioda-converters YAML for [3D]-RTMA ADPUPA BUFR
  test/CMakeLists.txt
  test/testinput/bufr_ncep_rtma_adpupa.yaml
  test/testinput/rtma.t00z.adpupa.tm00.bufr_d
  test/testoutput/rtma.t00z.adpupa.tm00.nc
Labels: OBS, NWS

#1455 Merge all OSW converters
  src/hdf5/cygnss_2ioda.py
  src/hdf5/muon_2ioda.py
  src/hdf5/osw_2ioda.py
Labels: OBS

#1458 Correct MetaData for pressure in ADPUPA YAML
  test/testinput/bufr_ncep_rtma_adpupa.yaml
  test/testoutput/rtma.t00z.adpupa.tm00.nc
Labels: OBS

#1463 fixed the precision of TropOMI CO pressureVertice
  src/compo/tropomi_no2_co_nc2ioda.py
  test/testoutput/tropomi_co_total.nc
Labels: needs review, COMPO

#1467 Fixed acprofile test failure and some other things.
  src/bufr/BufrParser/Query/Data.h
  src/bufr/BufrParser/Query/ResultSet.cpp
  test/CMakeLists.txt
  test/testinput/bufr_ncep_prepbufr_aircft.yaml
Labels: needs review, OBS, NWS

#1461 Update cris to cris-fsr in NCAR converter
  src/ncar-bufr2nc-fortran/define_mod.f90
  src/ncar-bufr2nc-fortran/radiance_mod.f90
Labels: coordinate merge, ready for merge, INFRA

#1453 YAML, input prepBUFR, and output IODA file for [3D]-RTMA ADPUPA prepbufr
  test/CMakeLists.txt
  test/testinput/bufr_ncep_rtma_prepbufr_adpupa.yaml
  test/testinput/rtma_ADPUPA.prepbufr
  test/testoutput/gdas.t00z.rtma_adpupa.prepbufr.nc
Labels: OBS, NWS

#1469 Fixing unit conversion inside the balloon sonde converter
  src/conventional/balloon_sonde_json2ioda.py
Labels: OBS

#1472 smap ssm date parse change
  src/land/smap_ssm2ioda.py
Labels: LAND
