Repository JCSDA-internal/ioda-converters, pull requests merged in 2024-05, with the labels that each got.

#1490 Update satbias upgrader for additional naming changes
  src/gsi_varbc/satbias_upgrader.py
Labels: OBS

#1357 PR for varBC sprint
  CMakeLists.txt
  src/CMakeLists.txt
  src/compo/viirs_biaswriter.py
  src/gsi_varbc/CMakeLists.txt
  src/gsi_varbc/CPPLINT.cfg
  src/gsi_varbc/GsiAircraftBiasConverter.cc
  src/gsi_varbc/GsiAircraftBiasReader.cc
  src/gsi_varbc/GsiAircraftBiasReader.h
  src/gsi_varbc/GsiSatBiasReader.cpp
  src/gsi_varbc/GsiSatBiasReader.h
  src/gsi_varbc/README.md
  src/gsi_varbc/SatBiasConverter.cpp
  src/gsi_varbc/generate_aircraft_bias_csv.py
  src/gsi_varbc/satbias_upgrader.py
  src/satbias/CMakeLists.txt
  test/CMakeLists.txt
  test/testinput/acftbias_converter.yaml
  test/testinput/satbias_converter.yaml
  test/testinput/satbias_converter_amsua.yaml
  test/testinput/satbias_converter_cris.yaml
  test/testinput/satbias_converter_gmi_gpm.yaml
  test/testinput/satbias_converter_ssmis.yaml
  test/testoutput/satbias_amsua_n18.nc4
  test/testoutput/satbias_cris_npp.nc4
  test/testoutput/satbias_gmi_gpm.nc4
  test/testoutput/satbias_ssmis_f16.nc4
  test/testoutput/varbc/acft_out.nc4
  test/testoutput/varbc/satbias_amsua_n18.nc4
  test/testoutput/varbc/satbias_cris_npp.nc4
  test/testoutput/varbc/satbias_gmi_gpm.nc4
  test/testoutput/varbc/satbias_ssmis_f16.nc4
  test/testoutput/varbc/viirs_bias.nc
  test/testoutput/viirs_bias.nc
Labels: ready for merge, code sprint

#1509 add sample_flags for osw
  src/hdf5/osw_2ioda.py
Labels: ready for merge, OBS

#1505 initial gnss derived tec decoder
  src/gnssro/gnss_tec_bufr2ioda.py
Labels: OBS, NAVY

#1514 merge smap9km modifications into original converter
  src/land/CMakeLists.txt
  src/land/smap_ssm2ioda.py
  test/CMakeLists.txt
  test/testoutput/smap9km_ssm.nc
  test/testoutput/smap_ssm.nc
Labels: needs review, OBS

#1516 tidy up smap converter
  src/land/smap9km_ssm2ioda.py
  test/CMakeLists.txt
  test/testoutput/smap9km_ssm.nc
  test/testoutput/smap_nrt_ssm.nc
  test/testoutput/smap_ssm.nc
Labels: needs review, LAND

#1518 Change the predictor emissivityK to emissivityJacobian following the naming convention
  test/testinput/satbias_converter.yaml
  test/testinput/satbias_converter_amsua.yaml
  test/testinput/satbias_converter_cris.yaml
  test/testinput/satbias_converter_gmi_gpm.yaml
  test/testinput/satbias_converter_ssmis.yaml
  test/testoutput/varbc/satbias_amsua_n18.nc4
  test/testoutput/varbc/satbias_cris_npp.nc4
  test/testoutput/varbc/satbias_gmi_gpm.nc4
  test/testoutput/varbc/satbias_ssmis_f16.nc4
Labels: bug, ready for merge, OBS

#1519 Update converter for last TEMPO public release
  src/compo/tempo_nc2ioda.py
  test/testoutput/tempo_no2_stratosphere.nc
  test/testoutput/tempo_no2_total.nc
  test/testoutput/tempo_no2_troposphere.nc
Labels: ready for merge, COMPO
