Repository JCSDA-internal/ioda-converters, pull requests merged in 2025-03, with the labels that each got.

#1620 Add PACE UAA AOD converter
  src/compo/CMakeLists.txt
  src/compo/pace_aod2ioda.py
  test/CMakeLists.txt
  test/testinput/pace_uaa_aod.2024072114.nc
  test/testoutput/pace_uaa_aod.2024072114.nc
Labels: ready for merge, COMPO

#1619 Update metar_csv2ioda converter for ISU data
  src/conventional/metar_csv2ioda.py
  test/CMakeLists.txt
  test/testinput/2025022218_metars_small.csv
  test/testinput/2025022218_metars_small.nc
  test/testoutput/2025022218_metars_small.nc
Labels: needs review, INFRA

#1615 Updated geoval names in the convertor for GSI nc_diag files.
  src/gsi_ncdiag/gsi_ncdiag.py
Labels: OBS, NWS

#1632 lengthen station identification to 8 characters for aircraft
  src/ncar-bufr2nc-fortran/prepbufr_mod.f90
  test/testoutput/radiosonde_obs_2020093018.nc4
Labels: OBS

#1629 fix the timeoff reading issue
  src/bufr/BufrParser/Exports/Variables/TimeoffsetVariable.cpp
Labels: bug, ready for merge, OBS

#1608 use the forward flag in the data to determine negative viewing angles
  src/hdf5/tropics_2ioda.py
  test/testinput/tropics_2022021600.nc
  test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4
Labels: OBS

#1636 Update _FillValue attributes and dateTime variable
  src/compo/aeronet_aaod2ioda.py
  src/compo/aeronet_aod2ioda.py
  test/testoutput/aeronet_aaod.nc
  test/testoutput/aeronet_aod.nc
Labels: ready for merge, COMPO
