Repository JCSDA-internal/ioda-converters, pull requests merged in 2025-05, with the labels that each got.

#1651 Fixing the conflict on case-insensitive file systems for TEMPO NO2 files
  test/CMakeLists.txt
  test/testoutput/tempo_no2_total.nc
  test/testoutput/tempo_no2_troposphere.nc
Labels: ready for merge, OBS, COMPO

#1653 Adding a check for invalid altimeter settings
  src/conventional/metar_csv2ioda.py
Labels: OBS, INFRA

#1612 SSMIS upp decoder
  src/hdf5/ssmis_upp_2ioda.py
Labels: NAVY
